# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: mv dist ~
    - run: cd ~/dist
    - run: git config --global user.email "gilphilbert@protonmail.com"
    - run: git config --global user.name "gilphilbert"
    - run: git init
    - run: git add -A
    - run: git commit -m 'Autodeploy'
    - run: git push -f https://gilphilbert:${{ secrets.GITHUB_TOKEN }}@github.com/gilphilbert/jukestudio.git master:dist
